/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Whispercpp_WhisperJNI */

#ifndef _Included_org_Whispercpp_WhisperJNI
#define _Included_org_Whispercpp_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Whispercpp_WhisperJNI
 * Method:    transcribeAudio
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Whispercpp_WhisperJNI_transcribeAudio
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
